feat: GotEnzymes database handling and deployment
MetabolicAtlas/MetabolicAtlas pull request #1036
Opened 2022-06-20 14:49 UTC by e0

**Related issue(s) and PR(s)**  
This PR closes #1023.

**Type of change**  

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
 
**List of changes made**  

- Update database schema including indexes.
- Use more performant lookup for semicolon separate fields (`ec_number` field from the `enzymes` table).
- Add remote docker compose configuration for the GotEnzymes database (`pg` container).
- Remove `km` from the enzymes table on the frontend
- Fix a bug where enzymes table are requested twice on initial page load
- Add section about GotEnzymes in the README.

**Testing**  

- Relative urls that can be reused both for production and local testing
- Instructions on how to test

1. Reconstruct the database: `ma-exec pg psql -f scripts/init.sql -U postgres`. This should take a while, it was around ~10 minutes for me.
2. Visit an entity's details page. For example:
  - `/enzymedb/compound/C00002`
  - `/enzymedb/ec/2.5.1.19`
  - `/enzymedb/reaction/R00006`
3. Verify that the basic info and cross references (not available for ec) tables are displayed.
4. Verify that the enzymes table is displayed. Please try out the filters (must be exact match), table sorting and pagination and verify that they work as expected.

**Further comments**  

- There is [some comments](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1023#issuecomment-1158795112) on the issue page that includes some more notes of research and findings when working on this issue.
- We were discussing the possibility of using a hash or flag to indicate if the deploy should include the database import. It seems that the deployment setup proposed in this PR has minimal impact on the deployment time so I don't think it's currently necessary to add this. More thorough explanation is provided in the comments linked above.

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

2022-06-20 14:50 UTC, e0 commented
This PR is set to Draft mode as it is based on the landing page work, which should be merged first.

2022-06-21 09:53 UTC, MalinAhlberg approved these changes
Great job!

This works well on my machine and think the setup sounds nice!

2022-06-21 13:03 UTC, mihai-sysbio requested changes
Looks good overall but there some things that might warrant another look.
Random question: I couldn't immediately understand the different purposes of `init.sql` and `init-schema.sql`, is there a reasonable way to avoid the code duplication?

FYI there is now an `enzymes.zip` archive with the raw files without the extra tab which  does not need extra pruning. 

_Note: importing with `ma-exec` took around 14 min on my machine._

2022-06-21 13:24 UTC, e0 commented on docker-compose-local.yml
> +    image: postgres:14.3-alpine
This is needed because it is no longer defined in the base `docker-compose.yml` anymore. The remote one uses a custom `Dockerfile`.

2022-06-21 13:26 UTC, e0 commented on pg/scripts/init-schema.sql
>  -- ma-exec pg psql -f scripts/init-schema.sql -U postgres
It looks pretty self explanatory to me. Or do you mean what the contents of the script file does?

2022-06-22 06:40 UTC, mihai-sysbio commented on docker-compose-local.yml
> +    image: postgres:14.3-alpine
But what stops us from using the same `Dockerfile` locally?

2022-06-22 06:42 UTC, mihai-sysbio commented
> How much resources have you allocated to Docker?

The Docker dashboard says 6/12 CPUs and 9Gb RAM. From what I could see in the `docker stats`, the `cpu` was maxing out, but not the RAM.

2022-06-22 07:51 UTC, mihai-sysbio approved these changes

2022-06-22 08:33 UTC, merged