Fix: Remove unused code
MetabolicAtlas/MetabolicAtlas pull request #1304
Opened 2023-03-10 10:31 UTC by perjo

**Related issue(s) and PR(s)**  
This PR closes https://app.zenhub.com/workspaces/metatlas-sprint-607745622d49260019ce115a/issues/gh/metabolicatlas/private-issues/37

**Type of change**  
- [ ] Other: Removal of unused code 
 
**List of changes made**  

Removed code which seems not to be used. 

**Screenshot of the fix**  

**Testing**  

Regression test the whole application. 

**Further comments**  

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

2023-03-13 15:03 UTC, pdmnyberg requested changes
The comment here: https://github.com/MetabolicAtlas/MetabolicAtlas/blob/a0ac18f4ca71f5de03d2a81281a015814ad358e9/frontend/src/components/explorer/interactionPartners/DetailsPage.vue#L439 makes no sense when `prepareHighlight is removed.

2023-03-13 15:59 UTC, pdmnyberg commented
Other than my comment above I think this looks good. I have done some clicking around to check that things work as expected and I have snooped at bit at the relevant source files in order to get a grip what has been done.

Good work.

2023-03-14 09:34 UTC, jonandernovella approved these changes

2023-03-14 11:35 UTC, pdmnyberg approved these changes
LGTM

2023-03-14 11:36 UTC, merged

2023-03-14 11:55 UTC, mihai-sysbio commented
I'm confused about the merging of this PR.
The original issue also lists some CSS that I had expected to also see removed. Was that meant to be resolved in a different issue/PR?

2023-03-14 12:27 UTC, mihai-sysbio reviewed
I've used my knowledge of the website to try out less obvious behaviors, and I have encountered some bugs. Without looking more into the changes and comparing with `main`, I can't tell if they have been introduced here or not.

2023-03-14 12:27 UTC, mihai-sysbio commented on frontend/src/components/Repository.vue
> -    },
Could you please make sure this removal doesn't hinder accessing `/gems/repository/Human-GEM`? Going to the Repository page directly and clicking on a model works, but going to the URL directly does not seem to work. If it was a problem on main, please report this new issue.

2023-03-14 12:27 UTC, mihai-sysbio commented on frontend/src/components/explorer/interactionPartners/DetailsPage.vue
> -    isCompartmentSubsystemHLDisabled() {
It would be nice to also remove the now-irrelevant `// TODO` above.

2023-03-14 12:27 UTC, mihai-sysbio commented on frontend/src/store/modules/compare.js
> -  resetComparisonDetails({ commit }) {
When playing around on the Comparison page, I managed to end up in confusing situations twise.

First, the table contains outdated information.
<img width="441" alt="image" src="https://user-images.githubusercontent.com/23480589/224999885-e9cef554-31e2-47ad-b505-42ed58784bc4.png">

Second, the comparison details on the right do not match what's on the left side.
<img width="852" alt="image" src="https://user-images.githubusercontent.com/23480589/224999579-b56d46b3-3207-433a-a4b1-6d8d5a82504b.png">

If this has not been introduced by these changes, please report as a new issue.

2023-03-14 14:37 UTC, perjo commented
I think we'd better revert this whole change. With no tests and no type safety and no knowledge of the application this seems to be impossible to do without risk of breaking something.