Add Global search button
MetabolicAtlas/MetabolicAtlas pull request #1344
Opened 2023-04-06 10:20 UTC by jonandernovella

This button is now added to the GEM search section and gives access to the global search feature.

2023-04-06 11:02 UTC, pdmnyberg requested changes

2023-04-06 11:36 UTC, pdmnyberg reviewed
While I think this solves the problem of making the global search easier to find I am not sure I like the way it affects the space available in the mobile view. Could we find a way that still maintains the old size of the text-input?

I think the issue had some suggestions where the button was show as a `part` of the text-input where I would expect it to disappear when selecting the input or when typing starts.

2023-04-11 06:56 UTC, jonandernovella commented
> While I think this solves the problem of making the global search easier to find I am not sure I like the way it affects the space available in the mobile view. Could we find a way that still maintains the old size of the text-input?
> 
> I think the issue had some suggestions where the button was show as a `part` of the text-input where I would expect it to disappear when selecting the input or when typing starts.

Pros with this solution:
- Global search button always shown, great for accessibility

Cons
- Shrunk input field

-----

Pros with suggested solutions in the issue
- Better use of space

Cons
- Limited accessibility: button won't be accessible when user is typing/has typed
- Button inside an input field that was designed for something else. Could confuse the user.

2023-04-11 07:02 UTC, perjo commented on frontend/src/components/explorer/gemBrowser/GemSearch.vue
> +      >
Surely we should use a `routerLink` instead of an ordinary `a` element to avoid full page reload?

2023-04-11 10:29 UTC, jonandernovella commented
@perjo and I did pair programming and we did some accessibility improvements:

- No page reload when clicking on global search
- Accessibility labels
- Moved button to the right end
- Improved quick search notification text about global search

2023-04-11 13:53 UTC, perjo approved these changes
Looks good (was pair programming)

2023-04-11 15:18 UTC, pdmnyberg approved these changes

2023-04-11 15:23 UTC, merged