Improve accessibility of search components and documentation
MetabolicAtlas/MetabolicAtlas pull request #1350
Opened 2023-04-12 13:36 UTC by jonandernovella

**Related issue(s) and PR(s)**  
This PR closes #943 

**Type of change**  

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other
 
**List of changes made**  

- Added component for connection documentation with web components
- Implemented this component in search and data overlay
- Minor accessibility improvements: role tags

**Screenshot of the fix**  

![image](https://user-images.githubusercontent.com/3052170/231474526-bbdbdd46-5251-46fe-89cd-c097f0d7d58a.png)

**Testing**  

- npx cypress run cypress -b firefox --spec cypress/e2e/helpbutton.cy.js
- Visit quick search and global search pages. Also, check the data overlay page

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

2023-04-12 14:10 UTC, perjo approved these changes
Looks good to me!

2023-04-13 08:47 UTC, KattisLej commented
Starting review

2023-04-13 09:28 UTC, KattisLej requested changes
* I left one accessibility comment on the help button and using the WAVE plugin to do so.

* I think the info icon could be a little bit bigger to be more visible:
![image](https://user-images.githubusercontent.com/105041852/231715252-14943745-2411-4a2d-a9d2-9688ac91efb4.png)
* Also the icon no longer has a cursor when hovering

* This is not from your changes but you could add this for accessebilty reason for improvement:
aria-label='search box' 
in the GemSearch.Vue inside the searchbox that begins with the input tag on row 21

Over all nice done, this is a very nice improvement

2023-04-13 09:28 UTC, KattisLej commented on frontend/src/components/shared/HelpButton.vue
> +  <button type="button" class="helpCircleButton" @click="redirectToPage()">
I checked the issue using the WAVE accessibility evaluation tool (https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) and it doesn't like the empty button, meaning the button has no text. Using:
aria-label='info button' 
inside button tag will fix that issue

2023-04-13 15:15 UTC, jonandernovella commented
>     * This is not from your changes but you could add this for accessebilty reason for improvement:
>       aria-label='search box'
>       in the GemSearch.Vue inside the searchbox that begins with the input tag on row 21

I think we already have done this with the role="searchbox"

2023-04-14 11:17 UTC, KattisLej approved these changes
Looks very nice and accessible :)

2023-04-14 13:37 UTC, merged

2023-04-14 13:40 UTC, Jessica-Sandler commented
This change adds some useful functionality and looks nice, and as far as I can see everything works as it is supposed to do. Good work!