feat: add overlay status indicator panel
MetabolicAtlas/MetabolicAtlas pull request #1351
Opened 2023-04-14 07:10 UTC by pdmnyberg

**Related issue(s) and PR(s)**  
This PR closes #975

Adds a panel indicating the overlay data status

**Type of change**  
- [x] New feature (non-breaking change which adds functionality)

**List of changes made**  
- Add an indicators getter to dataOverlay
- Add an indicator panel component
- Add indicator panel to mapviewer

**Screenshot of the fix**  
![Screen Shot 2023-04-13 at 18 00 11](https://user-images.githubusercontent.com/124560665/231818156-cc62b9c2-7874-4133-ae48-df26cc2336aa.png)

**Testing**  
- Go to: http://localhost/explore/Human-GEM/map-viewer/acylglycerides_metabolism?dim=2d&panel=0&sel=&search=&coords=-1973.35,-3529.21,0.18,0,0,500&dataTypes=gene,reaction&dataSources=hpaRna.tsv,HPA_single-cell_reactions.tsv&dataSets=adrenal%20gland,adipose%20tissue_fibroblasts_0
- Look for the panel in the lower right corner
- Change the overlays and verify that it is updated

**Definition of Done checklist**  
- [x] My code meets the Acceptance Criteria
- [x] My code follows the [NBIS style guidelines](https://github.com/NBISweden/development-guidelines)
- [x] I have performed a self-review of my own code and commented any hard-to-understand areas
- [x] Tests and lint/format validations are passing
- [x] My changes generate no new warnings

2023-04-18 10:56 UTC, jonandernovella requested changes
Looks great! I think we would benefit from having:

- A cypress test
- More descriptive name for:
  * the indicator panel component. I'd suggest DataOverlayIndicator
  * the groupsWithItems function could convey better what's really returning

2023-04-18 13:11 UTC, pdmnyberg commented
> Looks great! I think we would benefit from having:
> 
>     * A cypress test
> 
>     * More descriptive name for:
>       
>       * the indicator panel component. I'd suggest DataOverlayIndicator
>       * the groupsWithItems function could convey better what's really returning

I do not agree about the naming of the IndicatorPanel. I think it gets overly specific.

2023-04-18 13:36 UTC, jonandernovella commented
> > Looks great! I think we would benefit from having:
> > ```
> > * A cypress test
> > 
> > * More descriptive name for:
> >   
> >   * the indicator panel component. I'd suggest DataOverlayIndicator
> >   * the groupsWithItems function could convey better what's really returning
> > ```
> 
> I do not agree about the naming of the IndicatorPanel. I think it gets overly specific.

It should be specific in this case, I think. Otherwise it's very difficult to guess what this component is about and/or find it. Besides, if it shall be more generic that may be done at a later stage, at a later increment

2023-04-18 13:50 UTC, pdmnyberg commented
> > > Looks great! I think we would benefit from having:
> > > ```
> > > * A cypress test
> > > 
> > > * More descriptive name for:
> > >   
> > >   * the indicator panel component. I'd suggest DataOverlayIndicator
> > >   * the groupsWithItems function could convey better what's really returning
> > > ```
> > 
> > 
> > I do not agree about the naming of the IndicatorPanel. I think it gets overly specific.
> 
> It should be specific in this case, I think. Otherwise it's very difficult to guess what this component is about and/or find it. Besides, if it shall be more generic that may be done at a later stage, at a later increment when there's a use case for it.

I am still not convinced that making such specific components is a great approach. It makes it hard to know if reuse is possible/relevant. I think the component is easily found since it has a proper class in the DOM and it is referenced from the MapViewer component.

I am ok with renaming it but since we seem to disagree I would like a second opinion on this . @perjo @KattisLej

2023-04-19 09:23 UTC, KattisLej approved these changes
I think it looks very good and makes it easier to see. My only thought is the placement,  I am thinking if the right upper corner would make it more visible at least on larger screens. If you already tried that out and it didn't work, don't mind my comment.

As for the naming I think IndicatorPanel is a good name, I also think the other name suggestion could absolutely work but I don't think it's crucial to the understanding of the code.

2023-04-19 10:24 UTC, perjo commented
> > > >   * the indicator panel component. I'd suggest DataOverlayIndicator

So, the question is whether this is a general IndicatorPanel or a specific DataOverlayIndicator(Panel). I do not really have a strong preference. I myself would probably have used something like Jons proposal, but then I also have a feeling that I might often use too specific names...

2023-04-19 12:29 UTC, jonandernovella commented
> > > > > * the indicator panel component. I'd suggest DataOverlayIndicator
> 
> So, the question is whether this is a general IndicatorPanel or a specific DataOverlayIndicator(Panel). I do not really have a strong preference. I myself would probably have used something like Jons proposal, but then I also have a feeling that I might often use too specific names...

We discussed the component naming and decided the context of the component (folder location) is good enough for understanding the component.

2023-04-19 12:34 UTC, jonandernovella approved these changes

2023-04-19 12:37 UTC, merged