fix: on-click gene expression info icon to documentation
MetabolicAtlas/MetabolicAtlas pull request #540
Opened 2021-02-22 21:39 UTC by nanjiangshu

[x] direct to documentation by clicking the gene expression info icon

2021-02-23 14:30 UTC, mihai-sysbio requested changes
Good addition! I wouldn't have guessed that the blue color fits so well.

There is an indentation warning shown in `logs frontend`. We don't have automatic fixing of such cases, but it's on the roadmap MA-825.

When having a look at this on a half-screen window, the icon ended up alone on a next line. I think a <nobr> would "glue" it to the word before.

2021-02-25 12:02 UTC, nanjiangshu commented
> Good addition! I wouldn't have guessed that the blue color fits so well.
> 
> There is an indentation warning shown in `logs frontend`. We don't have automatic fixing of such cases, but it's on the roadmap [MA-825](https://chalmersysbiocsb.atlassian.net/projects/MA/issues/MA-825).
> 
> When having a look at this on a half-screen window, the icon ended up alone on a next line. I think a would "glue" it to the word before.

Hi, the indentation warning is fixed now. For the positioning of icon `i`, it moves as the layout of the webpage changes. Do you mean there is a way to bind the word `data` and the icon?

2021-02-25 17:34 UTC, mihai-sysbio commented
That's funny, the `<nobr>` tag  in my message was recognized by the markdown parser and it was hidden from the rendered html. Looking into this, [`<nobr>` is the best way to do this - `nowrap` should be used](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nobr). I tried this out in 15eef27630786203abe3ed4047d54e6638848836.

2021-02-25 19:25 UTC, nanjiangshu commented on frontend/src/components/explorer/mapViewer/DataOverlay.vue
> +      <span style="white-space: nowrap;">
nice solution!

2021-02-25 19:26 UTC, nanjiangshu commented on frontend/src/components/explorer/mapViewer/DataOverlay.vue
> +      <span style="white-space: nowrap;">
I think it is OK to merge now.

2021-02-26 06:49 UTC, merged