Feat/improve readme ma 834
MetabolicAtlas/MetabolicAtlas pull request #543
Opened 2021-03-15 11:53 UTC by nanjiangshu

Improving the README for Metabolic Atlas local deployment

- [x] added table of contents 
- [x] added instruction to add integrated GEMs
- [x] added instruction for how to modify the `.env` file

2021-03-16 11:18 UTC, e0 requested changes
@nanjiangshu This was great! It should improve the onboarding process a lot for new developers. Just have a small change request noted in the comments about changing `backend` to `api`. It was also nice for me to learn about `popd`.

2021-03-16 11:18 UTC, e0 commented on README.md
> +Given successful deployment, the frontend should be accessible at: `http://localhost/`. If you encounter any problems try running `restart-stack`, or look at the logs `logs backend` / `logs frontend`
In the updated stack, `backend` should be changed to `api`.

2021-03-16 11:18 UTC, e0 commented on README.md
>  * To display real-time logs: `logs [container-name: frontend/backend/nginx/db]`
In the updated stack, `backend` should be changed to `api`.

2021-03-16 12:07 UTC, e0 approved these changes

2021-03-16 17:33 UTC, mihai-sysbio reviewed
I've pushed a commit addressing all the points I had (see the extended message of that commit). The main focus was to streamline the Readme by making it more compact.
If all looks good to everyone, I'd say this is ready to be merged.

2021-03-16 17:33 UTC, mihai-sysbio approved these changes

2021-03-16 21:26 UTC, merged

2021-03-16 22:09 UTC, e0 commented
😕 Just saw these changes.. can't say I agree with the changes from https://github.com/MetabolicAtlas/MetabolicAtlas/pull/543/commits/08cc1ab9bc78b8fb36ea5536e4bf83ac0b5c44a9 , especially the removal of table of contents.

2021-03-17 05:11 UTC, mihai-sysbio commented
@e0 let's take this on Slack.