fix: code ql warnings
MetabolicAtlas/MetabolicAtlas pull request #621
Opened 2021-06-08 17:08 UTC by e0

2021-06-09 05:29 UTC, mihai-sysbio requested changes
Very nice to have started with this @e0!

> I simply removed the custom cache for 3D maps. For servers these should already being cached by nginx now.

If my memory serves me well, the caching can take around a minute per map, and the intention with caching in the backend was that we could trigger the caching from code after startup, instead of trying to squeeze these API calls among the first, in order to be cached. Regardless, I support the decision to remove the caching.

However, I think there's a timeout that needs updating - at least several compartment maps give throw an error, eg http://localhost/explore/Human-GEM/map-viewer/nucleus?dim=3d

2021-06-09 06:37 UTC, e0 commented
> However, I think there's a timeout that needs updating - at least several compartment maps give throw an error, eg http://localhost/explore/Human-GEM/map-viewer/nucleus?dim=3d 
> 

The map still needs to be loaded from scratch the first time it's requested even with the cache. For the server this change should not introduce any changes in performance at all. For local development, I believe you would get this timeout regardless of having the cache or not too. Do you want to open up a new issue for this?

2021-06-10 08:01 UTC, inghylt reviewed
Nice work, great to get this fixed!

All 3d maps worked for me except localhost/explore/Human-GEM/map-viewer/extracellular?dim=3d

That map works when building from develop

2021-06-11 06:19 UTC, mihai-sysbio commented
Commit daf85f2 increases the 60s timeout to 300s for the requests Nginx passes on to the API. All 3D maps should load successfully now, which I confirmed by loading the extracellular compartment. @inghylt could you have another look?

2021-06-11 06:20 UTC, mihai-sysbio approved these changes

2021-06-11 07:15 UTC, inghylt approved these changes
Nice, everything seem to work. The changes made to proj.sh requires a certain version of Docker, could be wise to update README.md regarding this

2021-06-11 07:26 UTC, mihai-sysbio commented
@e0 would you prefer an updated Readme.md or a reversal of the changes in `proj.sh`?

2021-06-11 08:04 UTC, e0 commented
Thanks for testing this and helping out. Still not sure why the map loading time would be different but adding the timeout does not hurt.

I think we can get by without the changes in proj.sh so I'm in favor of reverting it. We should probably have a new issue for consolidating on Docker version and updating this file if it makes sense (need to check if the new syntax works everywhere in proj.sh).

2021-06-11 08:39 UTC, merged